name: vfinally
description: VFinally VOD 

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.4.0
  cupertino_icons: ^0.1.2
  chewie: ^0.9.8+1
  video_player: ^0.10.5
  carousel_pro: ^1.0.0
  wakelock: ^0.1.3+3
  splashscreen: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - asset/
  #  - images/a_dot_ham.jpeg
